CREATE SCHEMA IF NOT EXISTS homework_6_test;
USE homework_6_test;

CREATE TABLE IF NOT EXISTS account_table (
  id BIGINT NOT NULL AUTO_INCREMENT,
  city VARCHAR(255) NULL DEFAULT NULL,
  country VARCHAR(255) NULL DEFAULT NULL,
  employee_count INT NOT NULL,
  industry VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS opportunity (
  id BIGINT NOT NULL AUTO_INCREMENT,
  account_id BIGINT NULL DEFAULT NULL,
  decision_maker BIGINT NULL DEFAULT NULL,
  product VARCHAR(255) NULL DEFAULT NULL,
  quantity INT NOT NULL,
  sales_rep_id BIGINT NULL DEFAULT NULL,
  status VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;